### ISSUE TITLE
CPU core filling /var/log/daemon log with constant log writings

### ISSUE THREAD

**Issue by ismoo1** [bartbutenaers/node-red-contrib-cpu#2] opened 2022-01-15 07:13 UTC
I deployed few days ago cpu, and thought I got it working as can get InfluxDB store and Grafana to show stats on Core specific load+ CPU overall load ((every second), Drives and temperature (every minute). However yet again once my PI got stuck and started to debugging that , found that daemon log is fast filling up, likely causing some extra load, with these log writings EVERY second. other CPU entries are not written, how come? In Node-red I switch off every debug messages and window stays empty.

Jan 15 08:58:04 raspberrypi Node-RED[447]: 15 Jan 08:58:04 - [info] [debug:raspi cpu]
Jan 15 08:58:04 raspberrypi Node-RED[447]: [
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_1',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 4,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_2',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 2,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_3',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 7,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_4',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 7,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   }
Jan 15 08:58:04 raspberrypi Node-RED[447]: ]
Jan 15 08:58:04 raspberrypi Node-RED[447]: 15 Jan 08:58:04 - [info] [debug:raspi cpu]
Jan 15 08:58:04 raspberrypi Node-RED[447]: [
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_1',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 4,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_2',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 2,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_3',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 7,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   },
Jan 15 08:58:04 raspberrypi Node-RED[447]:   {
Jan 15 08:58:04 raspberrypi Node-RED[447]:     name: 'core_4',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     usage: 7,
Jan 15 08:58:04 raspberrypi Node-RED[447]:     model: 'ARMv7 Processor rev 3 (v7l)',
Jan 15 08:58:04 raspberrypi Node-RED[447]:     speed: 600
Jan 15 08:58:04 raspberrypi Node-RED[447]:   }
Jan 15 08:58:04 raspberrypi Node-RED[447]: ]

**Comment by ismoo1** [comment] 2022-01-15 16:34
Answering myself, after further check noted another tag "system-console" in node-red debug window wchi I had accidentally enabled
![image](https://user-images.githubusercontent.com/93079872/149629752-6ccc2320-5e58-495c-aa5b-5fe8faa79c5f.png)

**Comment by bartbutenaers** [comment] 2022-01-15 19:56
Hi @ismoo1,
Thanks for sharing your feedback!
Good that you found it, because otherwise it could have been caused by all kind of changes in more recent NodeJs versions...
If everything is solved, please close this issue.

Kind regards,
Bart

**Comment by ismoo1** [comment] 2022-01-16 15:43
As explained found myself wrong debug settings

**Closed as completed** 2022-01-16 15:43 UTC
